# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:8.12.0

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy-staging:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - run:
        name: deploy to staging
        command: echo "staging"
      - run:
        name: deploy to prod
        command: echo "prod"


workflows:
  version: 2
  deploy-starter:
    jobs:
      - build-and-test
      - deploy-staging: # run deploy staging
          requires:
            - build-and-test
          filters:
            branches:
              only: test-circle # and only on the `develop` branch
