# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/ds-starter
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install NodeJs dependencies
          command: npm install
      - save_cache:
          name: Save node_modules to cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Generate static assets
          command: npm run build
      - persist_to_workspace:
          root: ~/ds-starter
          paths:
            - docs/
            - .deploy/
            - package.json
            - package-lock.json

  deploy-staging:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/ds-starter
      - run:
          name: Deploy staging to cloudgov.au
          command: |
            cd ~/ds-starter
            mkdir -p deploy/
            mv docs/ deploy/
            mv package.json deploy/
            mv package-lock.json deploy/
            mv .deploy/manifest-staging.yml deploy/
            cd deploy/
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cf zero-downtime-push ds-starter -f manifest-staging.yml

  deploy-test:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/ds-starter
      - run:
          name: Deploy staging to cloudgov.au
          command: |
            cd ~/ds-starter
            mkdir -p deploy/
            mv docs/ deploy/
            mv package.json deploy/
            mv package-lock.json deploy/
            mv .deploy/manifest-staging.yml deploy/
            cd deploy/
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cf zero-downtime-push ds-starter -f manifest-staging.yml

  deploy-prod:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/ds-starter
      - run:
          name: Deploy staging to cloudgov.au
          command: |
            cd ~/ds-starter
            mkdir -p deploy/
            mv docs/ deploy/
            mv package.json deploy/
            mv package-lock.json deploy/
            mv .deploy/manifest-staging.yml deploy/
            cd deploy/
            cf login -a $CF_API_PROD -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_PROD
            cf zero-downtime-push ds-starter -f manifest-staging.yml


workflows:
  version: 2
  deploy-starter:
    jobs:
      - build-and-test
      - deploy-staging: # run deploy staging
          requires:
            - build-and-test
          filters:
            branches:
              only: test-circle # and only on the `develop` branch

      - deploy-prod: # run deploy staging
        requires:
          - build-and-test
        filters:
          branches:
            only: master # and only on the `master` branch

      - deploy-test: # run deploy staging
        requires:
          - build-and-test
        filters:
          branches:
            only: /.*-test/ # and only on the `master` branch
